// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc5n6V2yCT3z4q1RGtOFTESun8FCRa17I',
    appId: '1:976775636394:web:ba6c20e6a0535249e6f7d3',
    messagingSenderId: '976775636394',
    projectId: 'jgpacktrack',
    authDomain: 'jgpacktrack.firebaseapp.com',
    storageBucket: 'jgpacktrack.firebasestorage.app',
    measurementId: 'G-0MEN3EBCKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk0EzcMrVyH4Km_xIyPYZbT8KQJBFGlEE',
    appId: '1:976775636394:android:c95c024bee1f9469e6f7d3',
    messagingSenderId: '976775636394',
    projectId: 'jgpacktrack',
    storageBucket: 'jgpacktrack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWMaDk5K9sl8Ki-S0qE32luMBzyJfN0uA',
    appId: '1:976775636394:ios:6726acd036ad7cf4e6f7d3',
    messagingSenderId: '976775636394',
    projectId: 'jgpacktrack',
    storageBucket: 'jgpacktrack.firebasestorage.app',
    iosBundleId: 'com.example.pjpacktrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWMaDk5K9sl8Ki-S0qE32luMBzyJfN0uA',
    appId: '1:976775636394:ios:6726acd036ad7cf4e6f7d3',
    messagingSenderId: '976775636394',
    projectId: 'jgpacktrack',
    storageBucket: 'jgpacktrack.firebasestorage.app',
    iosBundleId: 'com.example.pjpacktrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc5n6V2yCT3z4q1RGtOFTESun8FCRa17I',
    appId: '1:976775636394:web:662ab8b404ce2be0e6f7d3',
    messagingSenderId: '976775636394',
    projectId: 'jgpacktrack',
    authDomain: 'jgpacktrack.firebaseapp.com',
    storageBucket: 'jgpacktrack.firebasestorage.app',
    measurementId: 'G-1RJ8Q5R28T',
  );
}
